# Generated by Django 2.1.3 on 2019-02-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
                ('aboutjob', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
    ]
